/* Callback results */

#define ICD_TOR_DBUS_INTERFACE "org.maemo.Tor"
#define ICD_TOR_DBUS_PATH "/org/maemo/Tor"

#define ICD_TOR_SIGNALS_STATUS #ICD_TOR_DBUS_INTERFACE ".Status"

#define ICD_TOR_SIGNALS_STATUS_CONNECTED "Connected"
#define ICD_TOR_SIGNALS_STATUS_STARTED "Started"
#define ICD_TOR_SIGNALS_STATUS_STOPPED "Stopped"

// TODO: make this an enum
#define TOR_DBUS_METHOD_START_RESULT_OK 0
#define TOR_DBUS_METHOD_START_RESULT_INVALID_CONFIG 1
#define TOR_DBUS_METHOD_START_RESULT_ALREADY_RUNNING 2
#define TOR_DBUS_METHOD_START_RESULT_FAILED_TO_START 3
